$script_mysql = <<-SCRIPT
  apt-get update && \
  apt-get install -y mysql-server-5.7 && \
  mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT


Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end

    # config.vm.define "mysqldb" do |mysql|
    #   mysql.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8265", ip: "192.168.0.10"
    #   mysql.vm.provision "shell", inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys"
    #   mysql.vm.provision "shell", inline: $script_mysql
    #   mysql.vm.provision "shell", inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    #   mysql.vm.provision "shell", inline: "service mysql restart"
    #   mysql.vm.synced_folder "./configs", "/configs"
    #   mysql.vm.synced_folder ".", "/vagrant", disabled: true
    # end

    config.vm.define "phpweb" do |phpweb|
      phpweb.vm.provider "virtualbox" do |v|
        v.name = "ubuntu_bionic_phpweb"
      end
      phpweb.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8265", ip: "192.168.0.11"
      phpweb.vm.synced_folder "./configs", "/configs"
      phpweb.vm.provision "shell", inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys"
      phpweb.vm.provision "shell", inline: "apt-get update && apt-get install -y puppet"
      phpweb.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "./configs/manifests"
        puppet.manifest_file = "phpweb.pp"
      end
    end

    config.vm.define "mysqlserver" do |mysqlserver|
      mysqlserver.vm.provider "virtualbox" do |v|
        v.name = "ubuntu_bionic_mysqlserver"
      end
      mysqlserver.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8265", ip: "192.168.0.12"
      mysqlserver.vm.provision "shell", inline: "cat /vagrant/configs/id_bionic.pub >> .ssh/authorized_keys"

    end
    
    config.vm.define "ansible" do |ansible|
      ansible.vm.provider "virtualbox" do |v|
        v.name = "ubuntu_bionic_ansible"
      end
      ansible.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8265", ip: "192.168.0.9"
      ansible.vm.provision "shell", 
        inline: "cp /vagrant/id_bionic /home/vagrant && \
                 chmod 600 /home/vagrant/id_bionic && \
                 chown vagrant:vagrant /home/vagrant/id_bionic"
      ansible.vm.provision "shell", 
        inline: "apt-get update && \
                apt-get install -y software-properties-common && \
                apt-add-repository --yes --update ppa:ansible/ansible && \
                apt-get install -y ansible"
      ansible.vm.provision "shell", 
        inline: "ansible-playbook -i /vagrant/ansible/hosts /vagrant/ansible/playbook.yml"
    end
    
  end